apiVersion: v1
kind: Secret
metadata:
  name: bellboy-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  slack-token: {{ .Values.slack.token | quote }}
  slack-channel: {{ .Values.slack.channel | quote }}
