apiVersion: v2
name: bellboy
description: Kubernetes Deployment monitor with Slack notifications
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - kubernetes
  - deployment
  - monitoring
  - slack
maintainers:
  - name: myyrakle
