apiVersion: v2
name: bellboy
description: Kubernetes Deployment monitor with Slack notifications
type: application
version: 0.2.0
appVersion: "0.2.0"
keywords:
  - kubernetes
  - deployment
  - monitoring
  - slack
maintainers:
  - name: myyrakle
